### ISSUE TITLE
SOmBRA

### ISSUE THREAD

**Issue by DaviAragao** [mounter/Projeto-SOmBRA#1]
O projeto morreu?

**Comment by gil0mendes** [comment]
Oi, não! Mas tanto eu como o @mounter andamos extremamente ocupados este ano 😞 Não temos tido tempo para dedicar ao projeto neste momento.

Por exemplo, eu tenho o meu trabalho e ainda ando a realizar a tese de mestrado, o [Stellar](https://github.com/gil0mendes/stellar).
